# Jekyll configuration
markdown: kramdown
# kramdown 마크다운의 개선판임.

owner: 
  name:   mnmsoft
  avatar: 
  bio: 엠엔엠소프트 개발자


highlighter: rouge
#text highlighter로 rouge이용



paginate: 20 # it will paginate after this number
#한페이지에 몇개가 보여질것인지..

language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: https://mnmsoft.github.io
# sitemap 생성시 필요. disqus 를 사용할때에도 필요!

baseurl: /


# Website info
title: mnmsoft blog
description: 특별한 카톡메시지, 특별한 카톡편지, 이름궁합, 터치팡팡, 청기백기 등을 서비스하는 엠엠엠소프트의 개발입니다.
cover: assets/images/blog-cover.jpg
#블로그 홈에 표시되는 이미지

logo: assets/images/mnmlog.png #assets/images/blog-icon.png

logo_dark: assets/images/mnmlog.png #assets/images/favicon.png
favicon: assets/images/mnmlog.png #assets/images/favicon.png

production_url:  https://mnmsoft.github.io
source_url:  https://github.com/mnmsoft/mnmsoft.github.io


CNAME: #add cname for website to be created

# Social info
navigation: True # show the navbar links
subscribers: True 
# 검색용도로 사용할 예정

twitter: # replace by your username
facebook: # replace by your username

# Disqus
disqus: true
disqus_shortname: disqus_NxdOdkDZyY # replace with your disqus username

# Google Analytics
google_analytics: UA-173628111-1 # replace with your GA tracking identifier
#구글 어날리스틱


# Permalinks
permalink: /:title
# 글 제목으로 링크를 만들겠다..
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for building master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise

# 배포 필드 자동화...
safe: False
lsi: False
username: mnmsoft
repo: mnmsoft.github.io
branch: main
relative_source: 
destination: ../[GitHubPage]/
#컴파일 결과가 생성되는 폴더

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
#제외해야할 파일.
